import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { scheduleApi } from "@/lib/api/schedule";
import { notificationsApi } from "@/lib/api/notifications";
import { documentsApi } from "@/lib/api/documents";
import { settingsApi } from "@/lib/api/settings";
import { queryKeys } from "@/lib/queryKeys";
import { WorkflowError } from "@/components/workspace/workflow";
import { DashboardPanel } from "./dashboard-panel";

export function DashboardConnected({ org, slug }: { org: string; slug: string }) {
  const today = new Date(); today.setHours(0, 0, 0, 0); const next = new Date(today); next.setDate(next.getDate() + 7);
  const events = useQuery({ queryKey: ["events", org, today.toISOString(), next.toISOString()], queryFn: () => scheduleApi.list(org, today.toISOString(), next.toISOString()), retry: false });
  const activity = useQuery({ queryKey: ["notifications", org, "activity", 0], queryFn: () => notificationsApi.list(org, "activity"), refetchInterval: 30000, retry: false });
  const files = useQuery({ queryKey: ["documents", org], queryFn: () => documentsApi.list(org), retry: false });
  const billing = useQuery({ queryKey: queryKeys.billing(org), queryFn: () => settingsApi.billing(org), retry: false });
  return <><section className="grid gap-5 xl:grid-cols-2"><DashboardPanel title="This week's schedule" action={<Link className="text-xs text-primary" to="/$organizationSlug/schedule" params={{ organizationSlug: slug }}>Open calendar</Link>}><WorkflowError error={events.error} />{events.isPending && <p className="text-sm text-muted-foreground">Loading events…</p>}<div className="divide-y">{events.data?.slice(0, 5).map((event) => <div key={event.id} className="py-3"><p className="text-sm font-medium">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.startsAt).toLocaleString()}{event.location ? ` · ${event.location}` : ""}</p></div>)}</div>{events.data?.length === 0 && <p className="text-sm text-muted-foreground">No events planned for the next seven days.</p>}</DashboardPanel><DashboardPanel title="Recent activity" action={<Link className="text-xs text-primary" to="/$organizationSlug/notifications" params={{ organizationSlug: slug }}>View updates</Link>}><WorkflowError error={activity.error} />{activity.isPending && <p className="text-sm text-muted-foreground">Loading activity…</p>}<div className="divide-y">{activity.data?.items.slice(0, 5).map((item) => <div key={item.id} className="py-3"><p className="text-sm">{item.actor || "A teammate"} {item.verb.replaceAll("_", " ")} · {item.taskName}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div>{activity.data?.items.length === 0 && <p className="text-sm text-muted-foreground">Project activity will appear as your team works.</p>}</DashboardPanel></section><section className="grid gap-5 xl:grid-cols-2"><DashboardPanel title="Document storage" action={<Link className="text-xs text-primary" to="/$organizationSlug/documents" params={{ organizationSlug: slug }}>Open library</Link>}><WorkflowError error={files.error} />{files.isPending ? <p className="text-sm">Loading storage…</p> : files.data && <><p className="text-2xl font-semibold">{(files.data.reduce((sum, file) => sum + file.fileSize, 0) / 1048576).toFixed(1)} MB</p><p className="mt-2 text-xs text-muted-foreground">Stored files you can access, including trash. No storage quota is configured.</p></>}</DashboardPanel><DashboardPanel title="Workspace plan" action={<Link className="text-xs text-primary" to="/$organizationSlug/settings/billing" params={{ organizationSlug: slug }}>Billing</Link>}><WorkflowError error={billing.error} />{billing.isPending ? <p className="text-sm">Loading plan…</p> : billing.data && <><p className="text-lg font-semibold capitalize">{billing.data.plan} · {billing.data.status}</p><p className="mt-2 text-xs text-muted-foreground">{billing.data.members} of {billing.data.seatLimit} seats · {billing.data.agentLimit} agents included</p></>}</DashboardPanel></section></>;
}
