import { useState } from "react";
import { createFileRoute, useParams } from "@tanstack/react-router";
import { IconShieldCheck } from "@tabler/icons-react";
import { PageHeader } from "@/components/page-header";
import { Avatar, StatusPill } from "@/components/workspace-ui";
import { ResourceState } from "@/components/resource-state";
import { api, organizationPath, useApiResource } from "@/lib/api";
type Member = { id: string; role: string; user?: { name?: string; email?: string } };
type MemberResponse = Member[] | { members: Member[] };
export const Route = createFileRoute("/$tenant/settings/access")({ component: Access });
function Access() { const { tenant } = useParams({ strict: false }) as { tenant: string }; const result = useApiResource<MemberResponse>(organizationPath(tenant, "/members")); const [message, setMessage] = useState(""); const members = Array.isArray(result.data) ? result.data : result.data?.members ?? [];
  async function changeRole(memberId: string, role: string) { try { await api(organizationPath(tenant, "/members/update-role"), { method: "POST", body: JSON.stringify({ memberId, role: [role] }) }); setMessage("Role updated."); await result.reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to change role"); } }
  return <><PageHeader title="Access & roles" description="Review workspace membership and assign the appropriate organization role." /><ResourceState loading={result.loading} error={result.error} onRetry={result.reload} isEmpty={members.length === 0} emptyTitle="No members found">{members.length > 0 && <section className="surface overflow-hidden rounded-2xl"><div className="flex items-center gap-3 border-b p-5"><span className="grid size-9 place-items-center rounded-xl bg-violet-100 text-violet-700"><IconShieldCheck className="size-5" /></span><div><h2 className="font-semibold">Workspace roles</h2><p className="text-sm text-muted-foreground">Owners and admins can manage the team; members get day-to-day access.</p></div></div><div className="divide-y">{members.map((member) => <div key={member.id} className="flex flex-wrap items-center justify-between gap-4 p-4 sm:px-5"><div className="flex items-center gap-3"><Avatar name={member.user?.name ?? "Teammate"} /><div><p className="text-sm font-semibold">{member.user?.name ?? "Teammate"}</p><p className="text-xs text-muted-foreground">{member.user?.email ?? "Workspace member"}</p></div></div><div className="flex items-center gap-2"><StatusPill tone={member.role === "owner" ? "violet" : member.role === "admin" ? "amber" : "green"}>{member.role}</StatusPill><select value={member.role} onChange={(event) => void changeRole(member.id, event.target.value)} className="rounded-lg border bg-white px-2 py-1.5 text-sm"><option value="member">Member</option><option value="admin">Admin</option><option value="owner">Owner</option></select></div></div>)}</div></section>}</ResourceState>{message && <p className="mt-4 text-sm text-violet-700">{message}</p>}<section className="mt-6 rounded-2xl border border-violet-100 bg-violet-50/60 p-5"><h2 className="font-semibold">Permission model</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Roles grant module-level access. Document sharing and agent tool grants add narrower controls where needed, and every API request enforces organization membership.</p></section></>;
}
