import { Link } from "@tanstack/react-router";
import { IconArrowRight, IconCheck, IconFolder, IconPlus } from "@tabler/icons-react";
import type { Project } from "@/lib/api";
export function DashboardPage({ organizationSlug, organizationName, projects }: { organizationSlug:string; organizationName:string; projects:Project[] }) {
 const active=projects.filter(p=>p.status==="in_progress").slice(0,4);
 return <div className="mx-auto flex h-full w-full max-w-[1440px] flex-col gap-5 overflow-y-auto p-5 sm:p-6">
  <section className="flex flex-col gap-5"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Welcome back</h1><p className="mt-2 text-sm text-muted-foreground">Here is what is happening in {organizationName}.</p></div><div className="flex gap-2"><Link to="/$organizationSlug/tasks" params={{organizationSlug}} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground"><IconPlus className="size-4"/> New task</Link><Link to="/$organizationSlug/projects" params={{organizationSlug}} className="inline-flex h-10 items-center gap-2 rounded-lg border px-4 text-sm font-medium hover:bg-muted">Projects <IconArrowRight className="size-4"/></Link></div></div>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Projects",projects.length],["Active",active.length],["Completed",projects.filter(p=>p.status==="completed").length],["Planned",projects.filter(p=>p.status==="planned").length]].map(([label,value])=><div key={label as string} className="rounded-xl border bg-card p-5"><p className="text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{label}</p></div>)}</div></section>
  <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border bg-card p-5"><div className="mb-5 flex items-center justify-between border-b pb-4"><div><h2 className="font-semibold">Projects in motion</h2><p className="mt-1 text-sm text-muted-foreground">Your active projects and progress.</p></div><Link to="/$organizationSlug/projects" params={{organizationSlug}} className="text-sm text-primary">View all</Link></div>{active.length ? <div className="space-y-3">{active.map(p=><Link key={p.id} to="/$organizationSlug/projects/$projectId" params={{organizationSlug,projectId:p.identifier}} className="block rounded-lg border p-4 hover:bg-muted/40"><div className="flex justify-between gap-3"><span className="font-medium">{p.name}</span><span className="text-xs text-muted-foreground">{p.identifier}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:"35%"}}/></div></Link>)}</div>:<div className="py-12 text-center text-sm text-muted-foreground">No active projects yet.</div>}</section>
  <section className="rounded-xl border bg-card p-5"><div className="mb-5 border-b pb-4"><h2 className="font-semibold">Priority queue</h2><p className="mt-1 text-sm text-muted-foreground">Open work that needs attention.</p></div><div className="space-y-1">{["Review project progress","Follow up with your team","Create your next task","Check recent activity"].map((item,i)=><div key={item} className="flex items-center gap-3 rounded-lg px-3 py-4 hover:bg-muted/40"><div className="grid size-8 place-items-center rounded-full bg-muted"><IconCheck className="size-4"/></div><div><p className="text-sm font-medium">{item}</p><p className="text-xs text-muted-foreground">{i<2?"Needs attention":"Ready when you are"}</p></div></div>)}</div></section></div>
 </div>
}